# Generated by Django 4.2.8 on 2025-11-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, default='profiles/profile_default.png', null=True, upload_to='profiles/'),
        ),
    ]
