# Generated by Django 4.2.8 on 2025-10-31 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[[0, 'Perro'], [1, 'Gato'], [2, 'Hamster'], [3, 'Conejo'], [4, 'Pajaro'], [5, 'Tortuga']])),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'razas',
                'ordering': ('tipo',),
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('descripcion', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('edad', models.PositiveIntegerField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('en_adopcion', 'En adopcion'), ('adoptado', 'Adoptado')], default='en_adopcion', max_length=20)),
                ('public', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='Pets.especie')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Pets.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
