# Generated by Django 4.2.8 on 2025-10-31 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('adoptado', 'Adoptado'), ('en_adopcion', 'En adopcion')], default='en_adopcion', max_length=20),
        ),
    ]
