# Generated by Django 4.2.8 on 2025-11-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0002_alter_pet_image_alter_pet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('en_adopcion', 'En adopcion'), ('adoptado', 'Adoptado')], default='en_adopcion', max_length=20),
        ),
    ]
